// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssNVVzItpxc6gZOhu2GuKtcTzbabZq9A',
    appId: '1:818249687270:web:3257af497c6131f1849b27',
    messagingSenderId: '818249687270',
    projectId: 'grocery-app-d58a1',
    authDomain: 'grocery-app-d58a1.firebaseapp.com',
    storageBucket: 'grocery-app-d58a1.firebasestorage.app',
    measurementId: 'G-Y2KQV9JQ3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWVDn60mGpqLSl0JNrX9nZEBlSkEfNOhQ',
    appId: '1:818249687270:android:247b53a438b043c9849b27',
    messagingSenderId: '818249687270',
    projectId: 'grocery-app-d58a1',
    storageBucket: 'grocery-app-d58a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYBvRQ8oIsZ4Jz6Pakr-6RMo3NNWk720',
    appId: '1:818249687270:ios:ca56a09799d8aa3e849b27',
    messagingSenderId: '818249687270',
    projectId: 'grocery-app-d58a1',
    storageBucket: 'grocery-app-d58a1.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnYBvRQ8oIsZ4Jz6Pakr-6RMo3NNWk720',
    appId: '1:818249687270:ios:ca56a09799d8aa3e849b27',
    messagingSenderId: '818249687270',
    projectId: 'grocery-app-d58a1',
    storageBucket: 'grocery-app-d58a1.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCssNVVzItpxc6gZOhu2GuKtcTzbabZq9A',
    appId: '1:818249687270:web:d876931c0c2410c6849b27',
    messagingSenderId: '818249687270',
    projectId: 'grocery-app-d58a1',
    authDomain: 'grocery-app-d58a1.firebaseapp.com',
    storageBucket: 'grocery-app-d58a1.firebasestorage.app',
    measurementId: 'G-F94HLSJG1R',
  );
}
